# Generated by Django 4.0.5 on 2024-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga')], default='Particular', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat')], default='Ford', max_length=50),
        ),
    ]
